routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('admin/friends','FriendsController');

// Route::get('/','SiteControllar@welcome');
// Route::get('/home','SiteControllar@home');
// Route::get('/friend','SiteControllar@friend');
// Route::get('/friends','SiteControllar@query');
// Route::post('/form','SiteControllar@formHAndel');
Route::get('/profile','FriendsController@one');
// Route::get('/contact','SiteControllar@contact');
// Route::post('/contact','SiteControllar@contactAuth');
// Route::get('/post/{id}','SiteControllar@post');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Friend.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Friend extends Model
{
    protected $fillable = ['name','email','phone'];
    public function girlfirend(){
        return $this->hasMany('App\girlfirend','boyFriend','name');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/girlfirend.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;

class girlfirend extends Model
{
    public function boyfirend(){
        return $this->HasOne('App\Friend','name','boyFriend');
    }
}

app/query.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class query extends Model
{
   // protected $hidden = [   'created_at','updated_at'];
    protected $table = 'friends';
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FriendsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Friend;
use App\girlfirend;

class FriendsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
       $students = Friend::paginate(2);
       return view('admin.pages.index', compact('students'));
   }
    // public function index()
    // {
    //     $data = friend::all();
    //     return view('admin.pages.index',compact('data'));
    // }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Friend::create($request->all());
        return redirect (route('friends.index'))->with('success','insart successful');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = Friend::with('girlfirend')->find($id);
        return view('admin.pages.read', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Friend::find($id);
        return view('admin.pages.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id )
    {
        $data = Friend::find($id);
        $data->update($request->all());
        return redirect(route('friends.index'))->with('success','Update successful');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Friend::where('id',$id)->delete();
        return redirect()->back()->with('success','Delete successful');
    }
    // public function cheek(){
    //     $data = Friend::with('girlfirend')->where('name','shohel')->first();
    //     return view('profile',compact('data'));
    // }
    public function one(){
        $data = girlfirend::with('boyfirend')->find(4);
        return view('profile',compact('data'));
    }


}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SiteControllar.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SiteControllar extends Controller
{
    public function profile(){
        return view('profile');
    }
    public function home(){
        return view('home');
    }
    public function formHAndel(Request $request){
        $ruls = [
            'name' => 'required|min:5',
            'email' => 'required|email'
        ];
        $this->validate($request,$ruls);
        return $request->all();
    }

    public function welcome(){
        return view('welcome');
    }
    public function contact(){
        return view('contact');
    }
    public function friend(){
        return \App\friend::all();
    }
    public function query(){
        return \App\query::all();
    }
   
    public function contactAuth(Request$request){
        return "Your name is: ".$request->input('name');
    }
    
    public function post($id){
        return "Your id is: ".$id;
    }

    public function friends(){
        $students = DB::table('friends')->get();
        return view('profile', ['students' => $students]);
   }
//     public function index(){
//         $students = DB::table('friends')->get();
//         return view('profile', ['students' => $students]);
//    }
}

resources/views/admin/pages/create.blade.php
@extends('master')
@section('title')
view
@endsection
@section('contain')
    <div class="container">
    <h1>Insart Data</h1>
    <hr>
        <div class="card offset-3 col-md-6">
            <div class="card-body ">
            <form action="{{route('friends.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text" class="form-control" name='name' id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Your Name" require>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Email</label>
                    <input type="email" class="form-control" name='email' id="exampleInputPassword1" placeholder="Enter your Email" require >
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Phone</label>
                    <input type="number" class="form-control" id="exampleInputPassword1" placeholder="Enter your Phone Number" name='phone' require>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/edit.blade.php
@extends('master')
@section('title')
edit
@endsection
@section('contain')
    <div class="container">
    <h1>Insart Data</h1>
    <hr>
        <div class="card offset-3 col-md-6">
            <div class="card-body">
            <form action="{{route('friends.update',$user->id)}}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text" class="form-control" name='name' id="exampleInputEmail1" aria-describedby="emailHelp" value="{{$user->name}}" require>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Email</label>
                    <input type="email" class="form-control" name='email' id="exampleInputPassword1" value="{{$user->email}}"
                    require >
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Phone</label>
                    <input type="number" class="form-control" id="exampleInputPassword1" value="{{$user->phone}}" name='phone' require>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/index.blade.php
@extends('master')

@section('title')
friends index
@endsection

@section('contain')
    <div class="container">
        <div class="card">
        <div class="card-body">
        <h2>Data list</h2>
        <hr>
        <table class="table table-striped ">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Actions</th>
        </tr>


        @foreach($students as $row)
            <tr>
                <td>{{$row->name}}</td>
                <td>{{$row->email}}</td>
                <td>{{$row->phone}}</td>
                <td class="d-flex justify-content">
                    <a href="{{route('friends.show',$row->id)}}" type="button" class="btn btn-primary mr-1">View</a>
                    <a href="{{route('friends.edit',$row->id)}}" type="button" class="btn btn-secondary mr-1">Edit</a>
                    <form action="{{route('friends.destroy',$row->id)}}" method="post">
                        @csrf
                        @method('Delete')
                        <button class="btn btn-danger " type="submit">Delete</button>
                    </form>

                </td>
            </tr>
        @endforeach
        {{$students->links()}}
   </table>
        </div>
   </div>
    </div>

@endsection

resources/views/admin/pages/read.blade.php
@extends('master')
@section('title')
view
@endsection
@section('contain')
    <div class="container">
        <div class="row">
            <div class="card offset-1 col-md-5">
                <div class="card-body">
                    <table class=" table table-striped">
                        <tbody>
                            <tr>
                                <th >Name</th>
                                <td>{{$user->name}}</td>
                            </tr>
                            <tr>
                                <th >Email</th>
                                <td>{{$user->email}}</td>
                            </tr>
                            <tr>
                                <th >Phone</th>
                                <td>{{$user->phone}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card col-md-5">
                <div class="card-body">
                    <table class=" table table-striped">
                        <tbody>
                            <tr>
                                <th >GirlFirnds</th>
                            </tr>
                            @foreach ($user->girlfirend as $girl)
                            <tr>
                                <td>{{$girl->name}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contact.blade.php
@extends('master')

@section('title')
form
@endsection

@section('contain')
    <div class="form">
        <center>
        <h2>Contact</h2>
        <form action="{{url('/form')}}" method="post">
            @csrf
            <input type="text" name="name" placeholder="Name"><br><br>
            <input type="email" name="email" placeholder="Email"><br><br>
            <input type="submit" >
        </form>
        </center>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title') | laravel6</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body style="background:#EcEcec">
    <section class="bannar ">
    <nav class="navbar navbar-expand-lg navbar-light bg-primary ">
    <div class="container">
            <a class="navbar-brand" href="#">laravel6</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse float-right  " id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

            </ul>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link font-weight-bold" href="{{route('friends.index')}}">List <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link font-weight-bold " href="{{route('friends.create')}}">insart <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    </section>
    @if(Session::has('success'))
        <h4 class='text-center' style='color:green;'>{{Session::get('success')}}</h4>
    @endif
    <section class="main_contain">
        @yield('contain')
    </section>

    <hr>
    <section class="footer">
    <nav class="nav nav-pills nav-justified container">
        <h4 class="text-center" >This is just learing perpas web with laravel</h4>
    </nav>
    </section>
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/profile.blade.php
@extends('master')

@section('title')
    friends index
@endsection

@section('contain')
<p>{{$data->boyfirend->name}}</p>
<p>{{$data->boyfirend->email}}</p>
<p>{{$data->boyfirend->phone}}</p>

@endsection